---
name: Santiago
surname: Diaz Espitia
linkedin: "santiago-diaz-espitia-abb2661b5"
email: "diazespitiasantiago@gmail.com"
www: "www.sites.google.com/view/santiago-diaz-espitia"
github: SantiagoD999
phone: (+57) 3004045151
date: "`r format(Sys.time(), '%B %Y')`"
output: vitae::hyndman
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
```

# Education
```{r}
library(tibble)
tribble(
  ~ Degree, ~ Year, ~ Institution, ~ Where,
  "M.Res., Economic Analysis","Sep.2024-","Universidad Carlos III de Madrid", "Spain",
  "M.Sc., Economics (GPA: 4.95/5)","Jul.2022-Sep.2023","Pontificia Universidad Javeriana","Colombia",
  "B.Sc., Economics with a focus on Economic Theory (GPA: 4.75/5)", "Jul.2017-Mar.2022","Pontificia Universidad Javeriana","Colombia"
) %>% 
  detailed_entries(Degree, Year, Institution, Where)
```

# Research Interests
```{r}
tribble(
  ~Year,
  "Applied Macroeconometrics, Time Series Analysis, and Forecasting") %>% 
  detailed_entries(,Year)
```

# Awards

```{r}
tribble(
  ~Year,~Award,~Inst,~Why,
  "Sep.2023","Award for M.Sc. in Economics thesis","Pontficia Universidad Javeriana","For High Academic Standards",
  "Sep.2023","Academic Merit Order for M.Sc. in Economics","Pontificia Universidad Javeriana","For Outstanding Academic Performance",
  "Mar.2022","Academic Merit Order for B.Sc. in Economics","Pontificia Universidad Javeriana","For Outstanding Academic Performance",
  "May.2022","Best GPA in the 9th semester of the B.Sc. in Economics","Pontificia Universidad Javeriana","",
  "Jun.2021","ICFES Saber Pro (Educational State Test) Award","Pontificia Universidad Javeriana","",
  "Aug.2020","Best GPA in the 5th semester of the B.Sc. in Economics","Pontificia Universidad Javeriana","",
  "Mar.2019","Best GPA in the 3rd semester of the B.Sc. in Economics","Pontificia Universidad Javeriana","") %>% 
  detailed_entries(Award,Year,Inst,Why)
```


# Scholarships
```{r}

tribble(
  ~Year, ~Type, ~Inst,
  "Sep.2024-", "Graduate Program Scholarship", "Universidad Carlos III de Madrid",
  "Jul.2022-Dic.2022", "M.Sc. in Economics Scholarship", "Pontificia Universidad Javeriana"
) %>% 
  detailed_entries(Type,Year, Inst)

```


# Other Accomplishments

```{r}
tribble(
  ~Year,~Award,~Inst,~Why,
  "Dec.2020","5/5 grade in the Comprehensive Economics Exam","Pontficia Universidad Javeriana","Microeconomics, Macroeconomics, Econometrics, and Economic History") %>% 
  detailed_entries(Award,Year,Inst,Why)
```
# Publications

```{r}
tribble(
  ~Year, ~Title,
   "2023 M.Sc. in Economics Thesis","Forecasting Macroeconomic Series in Colombia: A Methodological Comparison Approach") %>% 
  brief_entries(Title, Year)
```

# Computer Skills

```{r}
tribble(
  ~Year,
  "Eviews, R, LATEX, Stata, Dynare, Python, Octave") %>% 
  detailed_entries(,Year)
```



# Teaching Experience

```{r}
tribble(
  ~Type,~Year,~Inst,
  "Teaching Assistant: Microeconomic Theory (Ph.D. level)","Feb.2020-Jun.2021", "Pontificia Universidad Javeriana",
  "Teaching Assistant: Advanced Macroeconomics (Undergraduate  level)","Aug.2020-Jun.2021", "Pontificia Universidad Javeriana"
  ) %>% 
  detailed_entries(Type,Year,Inst)
```

# Research Experience

```{r}
tribble(
  ~Type,~Year,~Inst,~Where,
  "Research Assistant: Department of Economics under Nicolás Lillo","Feb.2020-Dec.2020", "Pontificia Universidad Javeriana","",
  "Economic Research: Economic Research Department","Jan.2021-Jul.2022", "Banco Davivienda","Colombia",
  ) %>% 
  detailed_entries(Type,Year,Inst,Where)
```


# Languages

```{r}
tribble(
  ~Year,
  "Spanish (native), English (fluent)") %>% 
  detailed_entries(,Year)
```

# References

```{r}
library(tibble)
library(dplyr)
library(vitae)

# Create the data with LaTeX line breaks
data <- tribble(
  ~Year,
  "Gloria Lucia Bernal Nisperuza (Head of the Ph.D Program in Economics), Department of Economics, Pontificia Universidad Javeriana",
  "Christian Diego Alcocer Arguello (Associate Professor), Department of Accounting Sciences, Pontificia Universidad Javeriana",
  "Andrés Felipe Giraldo Palomino (Associate Professor), Department of Economics, Pontificia Universidad Javeriana",
  "Gonzalo Hernández Jiménez (Full Professor), Department of Economics, Pontificia Universidad Javeriana",
  "Andrés Langebaek Rueda (Chief Economics), Banco Davivienda",
)

# Render the CV with the formatted data
data %>%
  detailed_entries(,Year)

```

